import json, datetime

# 1. Fetch the data
try:
    with open('sofa.json', 'r') as f:
        data = json.load(f)
except Exception as e:
    print("Error reading the downloaded SOFA feed.")
    exit(1)

# Extract N and N-1
major_n = data['OSVersions'][0]
major_n_minus_1 = data['OSVersions'][1]

now = datetime.datetime.utcnow()

def calculate_deadline(release_date_str, grace_days=14):
    clean_date_str = release_date_str.split('T')[0]
    release_date = datetime.datetime.strptime(clean_date_str, '%Y-%m-%d')
    deadline_date = release_date + datetime.timedelta(days=grace_days)
    if deadline_date < now:
        deadline_date = now + datetime.timedelta(days=3)
    return deadline_date

# 2. Extract Version Numbers
def get_major_version_number(os_string):
    return os_string.split()[-1]

version_n = get_major_version_number(major_n['OSVersion'])
version_n_minus_1 = get_major_version_number(major_n_minus_1['OSVersion'])

deadline_n = calculate_deadline(major_n['Latest']['ReleaseDate'])
deadline_n_minus_1 = calculate_deadline(major_n_minus_1['Latest']['ReleaseDate'])
deadline_fallback = now + datetime.timedelta(days=7)

# 3. Build the JSON Requirements
requirements = [
    {
        "requiredMinimumOSVersion": major_n['Latest']['ProductVersion'],
        "requiredInstallationDate": deadline_n.strftime('%Y-%m-%dT00:00:00Z'),
        "targetedOSVersionsRule": version_n
    },
    {
        "requiredMinimumOSVersion": major_n_minus_1['Latest']['ProductVersion'],
        "requiredInstallationDate": deadline_n_minus_1.strftime('%Y-%m-%dT00:00:00Z'),
        "targetedOSVersionsRule": version_n_minus_1
    },
    {
        "requiredMinimumOSVersion": major_n_minus_1['Latest']['ProductVersion'],
        "requiredInstallationDate": deadline_fallback.strftime('%Y-%m-%dT00:00:00Z'),
        "targetedOSVersionsRule": "default"
    }
]

# 4. Save the nudge.json
nudge_dict = {
    "osVersionRequirements": requirements,
    "userExperience": {"nudgeRefreshCycle": 60, "approachingRefreshCycle": 240, "imminentRefreshCycle": 30, "approachingWindow": 10, "imminentWindow": 3, "randomDelay": False},
    "userInterface": {
        "updateElements": [{
            "_language": "en",
            "actionButtonText": "Update Now",
            "customAdmissionText": "Your device must meet minimum security standards.",
            "mainContentHeader": "Security Upgrade Required",
            "mainContentText": "To maintain access to company resources, your Mac must be upgraded to a supported version of macOS.",
            "mainHeader": "macOS Upgrade Required"
        }]
    }
}

with open('nudge.json', 'w') as f:
    json.dump(nudge_dict, f, indent=4)

# 5. GENERATE THE HUMAN-READABLE README
readme_content = f"""# 🚀 Automated Nudge Configuration

This repository automatically manages the macOS update requirements for our fleet. It syncs with the MacAdmins SOFA feed every morning at 8 AM UTC.

## 🛠 Current Compliance Policy
We follow an **N-1 Policy**, allowing users to remain on the previous major version as long as it is fully patched.

| Target Group | Target OS Version | Deadline | Action |
| :--- | :--- | :--- | :--- |
| **Current OS ({version_n})** | {major_n['Latest']['ProductVersion']} | {deadline_n.strftime('%b %d, %Y')} | Minor Patch |
| **Previous OS ({version_n_minus_1})** | {major_n_minus_1['Latest']['ProductVersion']} | {deadline_n_minus_1.strftime('%b %d, %Y')} | Minor Patch |
| **Unsupported (Old)** | {major_n_minus_1['Latest']['ProductVersion']} | {deadline_fallback.strftime('%b %d, %Y')} | **Major Upgrade** |

## 🔗 Live Links
* **Raw JSON Config:** [Click Here](https://raw.githubusercontent.com/mikelgorelo/nudge-config/main/nudge.json)
* **Last Updated:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}

---
*This README is auto-generated by `update_nudge.py`.*
"""

with open('README.md', 'w') as f:
    f.write(readme_content)

print("Nudge config and README generated successfully.")
