name: Update Nudge JSON
on:
  schedule:
    - cron: '0 8 * * *' # Runs every day automatically at 8 AM UTC
  workflow_dispatch: # Allows you to click a button to run it manually right now

# Silence the Node 20 deprecation warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch SOFA JSON Feed via cURL
        run: curl -sL --compressed -A "Nudge-Automation-Bot/1.0" "https://sofafeed.macadmins.io/v1/macos_data_feed.json" -o sofa.json

      - name: Run Python Script
        run: python update_nudge.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add nudge.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated Nudge OS version update" && git push)
